#!/bin/bash
/usr/bin/aws s3 sync s3://proger-52917 /var/www/html/
/bin/touch /var/spool/cron/root
sudo /bin/echo '*/5 * * * * /usr/bin/aws s3 sync s3://proger-52917 /var/www/html/' >> /var/spool/cron/root
